USE civicrm;

CREATE TABLE PracticeDetails (
	practice_code VARCHAR(16) NOT NULL,
	practice_name VARCHAR(500) NOT NULL
);

INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82063', 'East Leicester Med Pract(s Longworth) (C82063)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82029', 'Willowbrook Medical Centre (jg Astles) (C82029)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82088', 'Evington Medical Centre (c Kumar) (C82088)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82610', 'The Parks Medical Centre (b Hainsworth) (C82610)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82651', 'Broadhurst St Med Pract (ks Morjaria) (C82651)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82086', 'Fosse Medical Centre (gk Sharma) (C82086)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y00137', 'The Willows Medical Centre (Y00137)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82030', 'Downing Drive Surgery (ajj Bentley) (C82030)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82038', 'Latham House Medical Practice (C82038)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82022', 'The Billesdon Surgery (C82022)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82075', 'Castle Mead Medical Centre (C82075)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82024', 'Spinney Hill Medical Centre (C82024)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82015', 'Rushey Mead Health Centre (C82015)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82053', 'Hockley Farm Med Pract (a Nana) (C82053)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82059', 'Westcotes Gp Surgery (one) (C82059)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82678', 'Thurmaston Health Centre (C82678)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82092', 'Aylestone Health Centre (C82092)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82046', 'Saffron Group Practice (C82046)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82662', 'Walnut St Med Ctr (leicester Med Group) (C82662)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82094', 'Beaumont Lodge Medical Practice (C82094)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82018', 'Dr Sm Arolker & Partners (C82018)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82019', 'Pasley Road Health Centre (g Singh) (C82019)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82614', 'The Practice-asquith (C82614)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82671', 'Dr Gandecha & Partner (C82671)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82058', 'Saffron Surgery (C82058)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82639', 'Westcotes Health Centre (rl Hazeldine) (C82639)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82103', 'Dishley Grange Medical Practice (C82103)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82656', 'Field Street Surgery (C82656)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82047', 'Maples Family Med.pract. (C82047)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82667', 'The Charnwood Practice (C82667)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82620', 'Dr S Shafi (C82620)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82653', 'Westcotes Gp Surgery (two) (C82653)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82660', 'St Peter\'s Med Centre (mansingh & Mehra) (C82660)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82624', 'Beaumont Leys Health Centre (caretaker) (C82624)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82002', 'Countesthorpe Health Centre (C82002)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82065', 'The Maples Surgery (kp Newley) (C82065)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82124', 'Dr P Khunti & Partners (C82124)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82073', 'Merridale Medical Centre (rp Tew) (C82073)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03587', 'Westcotes Medical Centre (Y03587)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82034', 'Quorn Medical Centre (C82034)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82020', 'De Montfort Surgery (C82020)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82600', 'The Banks Surgery (C82600)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82068', 'Northfield Medical Centre (C82068)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82031', 'Johnson Medical Practice (C82031)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82114', 'Dr U K Roy (C82114)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82064', 'Forest House Surgery (C82064)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82033', 'Humberstone Medical Centre (ip Jones) (C82033)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82623', 'Heatherbrook Surgery (rp Archer) (C82623)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('c82099', 'St Peter\'s Road Surgery (ka Choudry) (C82099)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82037', 'East Park Medical Centre (rp Pandya) (C82037)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82107', 'Brandon Street Surgery (C82107)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82659', 'Melbourne Road Health Centre (r Kapur) (C82659)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82026', 'Bridge Street Medical Practice (C82026)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82021', 'The Central Surgery (C82021)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82010', 'Oakham Medical Practice (C82010)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C86040', 'Locum For Doncaster West Pct (C86040)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('G85114', 'Wells Park Practice (G85114)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82066', 'Forest House Medical Ctr (C82066)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('D81044', 'Nuffield Road Medical Centre (D81044)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('H84629', 'Village Surgery (H84629)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82040', 'Orchard Surgery (C82040)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82032', 'Dr Nw Osborne\'s Practice (C82032)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('E82071', 'Elms Medical Practice (E82071)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C83053', 'Colsterworth Surgery (C83053)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('D83050', 'Deben Road Surgery (D83050)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82093', 'The Orchard Med Practice (C82093)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82001', 'Kibworth Health Centre (C82001)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82009', 'Market Harborough Med.ctr (C82009)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82056', 'Glenfield Surgery (C82056)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82650', 'Desford Medical Centre (C82650)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('F83005', 'Gower Street Practice (F83005)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02560', 'Lps Moseley Medical Centre (Y02560)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82628', 'Groby Surgery (C82628)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82007', 'Castle Donington Surgery (C82007)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('J83026', 'Endless Street Surgery (J83026)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K84605', '9 King Edward Street (K84605)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C88007', 'Porter Brook Medical Centre (C88007)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83024', 'Dr Hanspaul & Partners (K83024)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82014', 'Ashby Health Centre (C82014)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82012', 'Ibstock House Surgery (C82012)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82013', 'Bushloe Surgery (C82013)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('E82054', 'Callowland Surgery (E82054)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82097', 'Charnwood Surgery (C82097)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82648', 'Hollycroft Medical Centre (C82648)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C84023', 'Cripps Health Centre (C84023)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82044', 'Empingham Medical Centre (C82044)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82041', 'Dr Gp Hanlon\'s Practice (C82041)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83016', 'Forest Gate Medical Centre (K83016)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('L84016', 'Frithwood Surgery (L84016)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C84703', 'The Gamston Medical Ctr. (C84703)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82003', 'Greengate Medical Centre (C82003)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82098', 'Hazelmere Medical Centre (C82098)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83006', 'Headlands Surgery (K83006)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82096', 'Hugglescote Surgery (C82096)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('F84647', 'Roserton Street Surgery (F84647)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82025', 'The Wycliffe Medical Practice (C82025)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C83649', 'Market Cross Surgery (C83649)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82028', 'Markfield Medical Centre (C82028)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('B82079', 'Stillington Surgery (B82079)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82008', 'Oakmeadow Surgery (ra Leach) (C82008)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83045', 'Dr Southcott And Partners (K83045)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('L83067', 'Sid Valley Practice (L83067)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('B85059', 'Slaithwaite Health Centre (B85059)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83018', 'Springfield Surgery (K83018)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82079', 'South Wigston Health Ctr. (C82079)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C84714', 'Sunrise Medical Practice (ghattaora) (C84714)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y00252', 'Dr Sjc Clay\'s Practice (Y00252)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('H82028', 'The Courtyard Surgery (H82028)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('P81067', 'The Healthcare Centre (P81067)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82055', 'The Limes Medical Centre (C82055)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C81051', 'The Park Medical Practice (C81051)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('B81109', 'Riverside Surgery (B81109)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('D81045', 'Buckden Surgery (D81045)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82649', 'Market Overton & Somerby Surgeries (C82649)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('D81615', 'Thorpe Road (D81615)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C88043', 'Tramways 54a Mc (C88043)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K81070', 'Twyford Surgery (K81070)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82077', 'The Uppingham Surgery (C82077)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K82037', 'Water Meadow Surgery (K82037)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83051', 'Weavers Medical (K83051)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82115', 'Dr Mj Reuben\'s Practice (C82115)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('D81031', 'Yaxley Group Practice (D81031)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('W92025', 'Dr Ja Davies\' Practice (W92025)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82642', 'Highfields Medical Centre (a Sinha) (C82642)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82643', 'Community Health Centre (zs Osama) (C82643)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82641', 'Station Road Surgery (C82641)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('W00010', 'Bro Taf Deputy (W00010)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82005', 'Groby Road Medical Centre (id Patchett) (C82005)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82611', 'The Masharani Practice (C82611)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('H81036', 'Parishes Bridge Med.pract (H81036)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82634', 'Ratby Surgery (C82634)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('D82088', 'Uea Medical Centre (D82088)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82680', 'The Practice-Rushey Mead (C82680)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82016', 'Long Clawson Medical Practice (C82016)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82050', 'Dr Nr Pulman\'s Practice (C82050)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C83653', 'The Stackyard Surgery (C83653)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('c83026', 'The Deeping Pracetice');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82095', 'Alpine House Surgery (C82095)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82042', 'County Practice (C82042)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82627', 'Dr Yb Shah\'s Practice (C82627)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82039', 'Kingsway Surgery (C82039)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82011', 'Pinfold Medical Practice (C82011)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82027', 'The Old School Surgery (C82027)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82644', 'Dr Mk Lakhani\'s Practice (C82644)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83077', 'Greenview Surgery (K83077)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82036', 'Dr Kilpatrick And Partners (C82036)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('D82027', 'Heacham Group Practice (D82027)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82100', 'The Hedges Medical Centre (sa Bailey) (C82100)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82067', 'The Croft Medical Centre (C82067)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82076', 'The Welby Practice (C82076)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C81068', 'Chapel Street Medical Centre (C81068)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82080', 'Shefa Medical Practice (C82080)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82070', 'Woodbrook Medical Centre (C82070)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('H81037', 'Birchwood Medical Practice (H81037)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('M82018', 'Beeches Medical Practice (M82018)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('B85037', 'Newsome Surgery (B85037)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82062', 'Barrow Health Centre (C82062)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('M85071', 'Wychall Lane Surgery (M85071)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C81091', 'Killamarsh Medical Practice (C81091)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K84074', 'Grove Medical Centre (K84074)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('A84045', 'Haydon Bridge & Allendale Medical Pract (A84045)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('L81007', 'The Southville Surgery (L81007)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C83068', 'The Little Surgery (C83068)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82051', 'Newbold Verdon Med.pract. (C82051)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('E82124', 'Attenborough Surgery (E82124)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82120', 'Dr Ea Hepplewhite\'s Practice (C82120)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('E87010', 'Maida Vale Medical Centre (E87010)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82102', 'Dr Heap & Partner (C82102)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02725', 'Oadby & Wigston Walk-in Centre (Y02725)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83019', 'The Long Buckby Practice (K83019)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82122', 'Clarendon Park Road Health Centre (C82122)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82052', 'Dr Am Lewis\' Practice (C82052)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82045', 'Dr Rw Lawrence\'s Practice (C82045)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82017', 'Measham Medical Unit (C82017)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82023', 'St Matthews Medical Centre (aia Lennox) (C82023)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82035', 'Park View Surgery (C82035)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82043', 'Station View Health Centre (C82043)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82048', 'Rosemead Drive Surgery (C82048)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82054', 'The Burbage Surgery (C82054)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82060', 'The Practice-sayeed (C82060)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82061', 'Barwell & Hollycroft Medical Centres (C82061)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82071', 'Wigston Central Surgery (C82071)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82072', 'Broom Leys Surgery (C82072)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82078', 'The Jubilee Medical Practice (C82078)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82081', 'Queens Road Medical Centre (C82081)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82082', 'The Centre Surgery (C82082)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82084', 'Dr B Modi (C82084)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82085', 'Hunters Lodge Medical Centre (C82085)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82091', 'Birstall Medical Centre (C82091)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82105', 'Ar-razi Medical Centre (C82105)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82106', 'The Family Practice (C82106)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82108', 'Long Street Surgery (C82108)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82109', 'The Husbands Bosworth Surgery (C82109)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82111', 'Nn Vaghela\'s Practice (C82111)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82112', 'Severn Surgery (C82112)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82116', 'Highfields Surgery (r Wadhwa) (C82116)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82119', 'Narborough Health Centre (C82119)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82121', 'Heath Lane Surgery (C82121)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82625', 'Petworth Drive Surgery (C82625)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82626', 'Pasley Road Health Centre (tk Khong) (C82626)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82631', 'Enderby Medical Centre (C82631)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82655', 'Dr Tm Hammond & Partners (C82655)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82657', 'Dr Bj Shah\'s Practice (C82657)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82663', 'Dr Sj Shepherd\'s Practice (C82663)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82669', 'The Surgery @ Aylestone (C82669)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82670', 'Inclusion Healthcare (C82670)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82676', 'St Elizabeth\'s Medical Centre (ja Wood) (C82676)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y00152', 'Loughborough Nhs Wic (Y00152)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y00247', 'Gpwsi Braunstone H & Scc (Y00247)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y00280', 'Belgrave Surgery (sv Bapodra) (Y00280)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y00344', 'Leicester City Assist Practice (Y00344)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y00980', 'City Ooh (Y00980)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y01651', 'New Parks Health Centre (Y01651)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y01785', 'Dermatology Clinic (Y01785)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y01872', 'Choices Service (Y01872)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02077', 'Leics & Rutland Ooh Service (Y02077)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02199', 'Lcr Community Drug Team 2 (Y02199)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02201', 'Leicester Recovery Partnership (Y02201)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02202', 'City Criminal Justice Drug Team (Y02202)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02305', 'Intermediate Care Drug Clinic (Y02305)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02365', 'Urgent Care Centre (Y02365)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02469', 'Ssafa Care Cic H & S (Y02469)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02470', 'Ssafa Care Cic Wic (Y02470)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02500', 'Northern Heights Medical Centre (Y02500)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02686', 'Bowling Green Street Surgery (Y02686)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03001', 'Integrated Community Diabetes Service (Y03001)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03321', 'Market Harborough Miu (Y03321)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03323', 'Melton Miu (Y03323)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03460', 'Children\'s Services (Y03460)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03715', 'Loughborough Urgent Care Centre (Y03715)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03761', 'Lpt Community Health Services Division (Y03761)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03909', 'Lpt Community Prescribers (Y03909)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03910', 'Lpt Community Prescribers (Y03910)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03956', 'Loros (Y03956)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y03957', 'Loros (Y03957)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04103', 'Loros (Y04103)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04111', 'Emergency Response Service (Y04111)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04310', 'Diabetes Specialist Nurse Service (Y04310)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04311', 'Diabetes Specialist Nurse Service (Y04311)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04312', 'Diabetes Specialist Nurse Service (Y04312)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C83024', 'The Glenside Country Practice (C83024)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C84696', 'West Oak Surgery (C84696)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('m85797', 'Hockley Medical Practice (M85797)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C86605', 'Askern Medical Practice (C86605)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('E82057', 'Ware Road Surgery (E82057)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83002', 'Dr Wilczynski & Partners (K83002)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C84648', 'Balderton Primary Care Centre (C84648)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83041', 'St Lukes Primary Care Centre (K83041)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C83017', 'St.mary\'s Medical Centre (C83017)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('F83045', 'The Miller Practice (F83045)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y00399', 'Dr Pasquali (Y00399)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C82682', 'Loughborough Road Medical Centre');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C83007', 'The New Sheepmarket Surg. (C83007)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C83080', 'The Harrowby Lane Surgery (C83080)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02197', 'County Cjdt (Y02197)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y02198', 'Lcr Community Drug Team 1 (Y02198)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('M87020', 'Feldon Lane Practice (M87020)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04811', 'Hinckley & Bosworth Medical Alliance (Y04811)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04813', 'Nwl Gps Ltd (Y04813)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('M84617', 'ARDEN MEDICAL CENTRE');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C83067', 'Long Bennington Surgery (C83067)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83026', 'Albany House (K83026)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83030', 'The Cottons Medical Centre (K83030)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C81028)', 'Imperial Road Surgery (C81028)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04879', 'Scgp Network Ltd Ooh (Y04879)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83052', 'Roade Medical Centre (K83052)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83013', 'Eskdaill Medical Centre (K83013)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K82009', 'Stony Medical Centre (K82009)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83021', 'Rothwell Medical Centre (K83021)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83014', 'Leicester Terrace H/CARE CTR( K83014)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83058', 'Clarence Avenue Surgery (K83058)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83027', 'Langham Place Surgery (K83027)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('C84680', 'RHR Medical Centre (C84680)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83044', 'Dr Hogg & partners (K83044)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83023', 'Oundle Medical Practice (K83023)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('K83036', 'Linden Ave Medical Centre (K83036)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('J81049', 'The Marine & Oakridge Partnership (J81049)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('J81646', 'Grove Surgery (J81646)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('A84021', 'Infirmary Drive Medical Group (A84021)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04973', 'Market Harborough Ucc (nduc) Ooh (Y04973)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04974', 'Melton Mowbray Ucc (nduc) Ooh (Y04974)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04975', 'Oadby Urgent Care Centre (nduc) Ooh (Y04975)');
INSERT INTO `PracticeDetails` (`practice_code`, `practice_name`) VALUES ('Y04976', 'Oakham Urgent Care Centre (nduc) Ooh (Y04976)');