version: '2'

services:
  etl:
    depends_on:
      - mysql
    links:
      - mysql:mysql

  web:
    depends_on:
      - mysql
    links:
      - mysql:mysql

  nginx:
    build:
      args:
        deployment_environment: development
    ports:
      - "80:80"

  mysql:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_MYSQL_RANDOM_ROOT_PASSWORD}
    expose:
      - "3306"