version: '2'

services:
  etl:
    depends_on:
      - mysql
    links:
      - mysql:mysql

  web:
    depends_on:
      - mysql
    links:
      - mysql:mysql

  nginx:
    restart: always
    build:
      context: ./nginx/
      args:
        deployment_environment: development
    depends_on:
      - web
    ports:
      - "80:80"
    volumes_from:
      - web:rw
    links:
      - web:web

  mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "True"
      MYSQL_DATABASE: ${GGPP_DB_NAME}
      MYSQL_USER: ${GGPP_DB_USER}
      MYSQL_PASSWORD: ${GGPP_DB_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"