version: '2'

services:
  etl:
    restart: always
    build: ./etl
    depends_on:
      - mysql
    links:
      - mysql:mysql
      - civicrmdb:civicrmdb
    environment:
      PORTAL_MYSQL_DATABASE: ${MYSQL_MYSQL_DATABASE}
      PORTAL_MYSQL_USER: ${MYSQL_MYSQL_USER}
      PORTAL_MYSQL_PASSWORD: ${MYSQL_MYSQL_PASSWORD}
      CIVICRM_MYSQL_DATABASE: ${CIVICRMDB_MYSQL_DATABASE}
      CIVICRM_MYSQL_USER: ${CIVICRMDB_MYSQL_USER}
      CIVICRM_MYSQL_PASSWORD: ${CIVICRMDB_MYSQL_PASSWORD}
      TAB_GP_CUSTOM: ${ETL_TAB_GP_CUSTOM}
      COL_GP_CODE: ${ETL_COL_GP_CODE}
      COL_GP_STATUS: ${ETL_COL_GP_STATUS}

  web:
    restart: always
    build: ./web
    depends_on:
      - mysql
    expose:
      - "8000"
    links:
      - mysql:mysql
    volumes:
      - /usr/src/app/portal/static
    environment:
      DEBUG: ${WEB_DEBUG}
      SECRET_KEY: ${WEB_SECRET_KEY}
      MYSQL_DATABASE: ${MYSQL_MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_MYSQL_PASSWORD}
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  mysql:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_MYSQL_RANDOM_ROOT_PASSWORD}
    expose:
      - "3306"

  civicrmdb:
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${CIVICRMDB_MYSQL_DATABASE}
      MYSQL_USER: ${CIVICRMDB_MYSQL_USER}
      MYSQL_PASSWORD: ${CIVICRMDB_MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${CIVICRMDB_MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - ./civicrm_seed:/docker-entrypoint-initdb.d
    expose:
      - "3306"