version: '2'

services:
  etl:
    restart: always
    build: ./etl
    depends_on:
      - mysql
    links:
      - mysql:mysql
      - civicrmdb:civicrmdb

  web:
    restart: always
    build: ./web
    depends_on:
      - mysql
    expose:
      - "8000"
    links:
      - mysql:mysql
    volumes:
      - /usr/src/app/portal/static
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - mysql:mysql
      - web:web

  mysql:
    restart: always
    image: mysql:latest
    env_file: .env
    expose:
      - "3306"

  civicrmdb:
    restart: always
    image: mysql:latest
    env_file: .civicrmdb_env
    volumes:
      - ./civicrm_seed:/docker-entrypoint-initdb.d
    expose:
      - "3306"